INSERT INTO PRODUCT VALUES (1, 'Product 1');
INSERT INTO PRODUCT VALUES (2, 'Product 2');
INSERT INTO PRODUCT VALUES (3, 'Product 3');
INSERT INTO PRODUCT VALUES (4, 'Product 4');
INSERT INTO PRODUCT VALUES (5, 'Product 5');